### ISSUE TITLE
Error with version 1.2.0

### ISSUE THREAD

**Issue by walberjunior** [rmoesbergen/openwrt#17]
Today I did a fresh install on my Archer C2 (OpenWrt 19.07.8) and after installing version 1.2.0.
I checked all the steps again but I couldn't solve it

```
Tue Jan 10 12:22:47 2023 daemon.err presence-detector.py[1971]: Traceback (most recent call last):
Tue Jan 10 12:22:47 2023 daemon.err presence-detector.py[1971]:   File "/etc/config/presence-detector.py", line 64, in <module>
Tue Jan 10 12:22:47 2023 daemon.err presence-detector.py[1971]:     class PresenceDetector(Thread):
Tue Jan 10 12:22:47 2023 daemon.err presence-detector.py[1971]:   File "/etc/config/presence-detector.py", line 195, in PresenceDetector
Tue Jan 10 12:22:47 2023 daemon.err presence-detector.py[1971]:     def stop(self, _signum: int | None = None, _frame: int | None = None):
Tue Jan 10 12:22:47 2023 daemon.err presence-detector.py[1971]: TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
Tue Jan 10 12:22:47 2023 daemon.info procd: Instance presence-detector::instance1 s in a crash loop 7 crashes, 3 seconds since last crash

```

Any idea?

**Comment by rmoesbergen** [comment]
@walberjunior Which python version are you running on your device?

**Comment by walberjunior** [comment]
I'm running these versions.

```
python3-base	3.7.13-1
python3-codecs	3.7.13-1
python3-email	3.7.13-1
python3-idna	2.9-1
python3-light	3.7.13-1
python3-urllib	3.7.13-1
```

I didn't install python3-requests, as I understand it won't be needed anymore

**Comment by rmoesbergen** [comment]
Hi @walberjunior , I just pushed a fixed for this. The | None syntax is not understood by older python versions. I've changed it to something more compatible. Please let me know if it works.

**Comment by walberjunior** [comment]
I remove the python3-requests and update the presence-detector.py.
Until now everything is OK. 
Thanks
