### ISSUE TITLE
Crash after restart HA

### ISSUE THREAD

**Issue by dckiller51** [rmoesbergen/openwrt#19]
Hi,
I always have a crash when I restart home assistant. Do you have any idea if it comes from my configuration?

```
Mon Jan 30 02:15:15 2023 daemon.err presence-detector.py[5315]: Exception in thread Thread-1:
Mon Jan 30 02:15:15 2023 daemon.err presence-detector.py[5315]: Traceback (most recent call last):
Mon Jan 30 02:15:15 2023 daemon.err presence-detector.py[5315]:   File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
Mon Jan 30 02:15:15 2023 daemon.err presence-detector.py[5315]:   File "/etc/config/presence-detector.py", line 210, in run
Mon Jan 30 02:15:15 2023 daemon.err presence-detector.py[5315]:     self.full_sync()
Mon Jan 30 02:15:15 2023 daemon.err presence-detector.py[5315]:   File "/etc/config/presence-detector.py", line 123, in full_sync
Mon Jan 30 02:15:15 2023 daemon.err presence-detector.py[5315]:     sync_ok &= self._ha_seen(client)
Mon Jan 30 02:15:15 2023 daemon.err presence-detector.py[5315]:   File "/etc/config/presence-detector.py", line 98, in _ha_seen
Mon Jan 30 02:15:15 2023 daemon.err presence-detector.py[5315]:     response = self._post(
Mon Jan 30 02:15:15 2023 daemon.err presence-detector.py[5315]:   File "/etc/config/presence-detector.py", line 81, in _post
Mon Jan 30 02:15:15 2023 daemon.err presence-detector.py[5315]:     with request.urlopen(req, timeout=5) as response:
Mon Jan 30 02:15:15 2023 daemon.err presence-detector.py[5315]:   File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
Mon Jan 30 02:15:15 2023 daemon.err presence-detector.py[5315]:   File "/usr/lib/python3.10/urllib/request.py", line 519, in open
Mon Jan 30 02:15:15 2023 daemon.err presence-detector.py[5315]:   File "/usr/lib/python3.10/urllib/request.py", line 536, in _open
Mon Jan 30 02:15:15 2023 daemon.err presence-detector.py[5315]:   File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
Mon Jan 30 02:15:15 2023 daemon.err presence-detector.py[5315]:   File "/usr/lib/python3.10/urllib/request.py", line 1377, in http_open
Mon Jan 30 02:15:15 2023 daemon.err presence-detector.py[5315]:   File "/usr/lib/python3.10/urllib/request.py", line 1352, in do_open
Mon Jan 30 02:15:15 2023 daemon.err presence-detector.py[5315]:   File "/usr/lib/python3.10/http/client.py", line 1374, in getresponse
Mon Jan 30 02:15:15 2023 daemon.err presence-detector.py[5315]:   File "/usr/lib/python3.10/http/client.py", line 318, in begin
Mon Jan 30 02:15:15 2023 daemon.err presence-detector.py[5315]:   File "/usr/lib/python3.10/http/client.py", line 279, in _read_status
Mon Jan 30 02:15:15 2023 daemon.err presence-detector.py[5315]:   File "/usr/lib/python3.10/socket.py", line 705, in readinto
Mon Jan 30 02:15:15 2023 daemon.err presence-detector.py[5315]: TimeoutError: timed out
```

**Comment by rmoesbergen** [comment]
Hi @dckiller51, thanks for the bugreport. It's not your settings, it's a bug... I'll push a fix shortly.
